#!/bin/bash
set -ouex pipefail

# Repository setup
curl -fsSL https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc \
    | gpg --dearmor | dd of=/etc/apt/trusted.gpg.d/linux-surface.gpg
echo "deb [arch=amd64] https://pkg.surfacelinux.com/debian release main" \
	| tee /etc/apt/sources.list.d/linux-surface.list

# Initial update
apt-get update -y

# Install Surface Bits
apt-get install -y \
	linux-image-surface \
	linux-headers-surface \
	libwacom-surface \
	iptsd \
	mokutil

# Build Initramfs
KERNEL_VERSION="$(basename "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E "*.img" | tail -n 1)")"
dracut --force --no-hostonly --reproducible --zstd --verbose \
  --kver "$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"

apt list --installed > /usr/share/snow/snowfield.packages.txt
